name: Build Flutter Android APK and Deploy to Internal Track

on: 
  workflow_call:
  push:
    branches:
      - main

jobs:

  build:
    if: github.event.pull_request.merged == true
    name: Create Android Build
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'upload-keystore.jks'
          encodedString: ${{ secrets.KEY_STORE }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.APP_NAME_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.APP_NAME_KEY }}" >> android/key.properties
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:         
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build AAB
        run: flutter build appbundle

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab

  deploy:
    name: Deploy Android Build
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Android Build from artifacts
      uses: actions/download-artifact@v3
      with:
        name: android-release
    - name: Release Build to internal track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_API_AUTH }}
        packageName: dev.almasum.family
        releaseFiles: app-release.aab
        track: internal
        status: draft
      
